### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [sjbcodes/teacozy#6]
**GRADE**: Needs Improvement

**SUMMARY**: Good work on this project. With a couple small tweaks the site will be looking great and you've done an excellent job keeping the project folder organized using separate folders for all of your resources. Great work using flex display to help align items throughout the page as well!

Behind the scenes, it is very important to use relative file paths to link to your locally saved images. Links to outside sources can easily become broken if that source decides to change where it is stored or take it down entirely. Also, keep an eye on your indentation to make sure it is consistent throughout. Clean, concise code is crucial and only becomes more so as your projects grow in size and complexity.

Great use of the header, nav, and footer semantic tags. As a next step, check out [this info](https://www.w3schools.com/html/html5_semantic_elements.asp) to see some other examples of tags you could use in future projects.	

Have fun and keep up the good work!

**Comment by sjbcodes** [comment]
Thanks for your feedback, very helpful. I tried to keep an eye on my indenting but looks like I should have gone over it one more time.
